### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by f-mio** [f-mio/protospace-32852#1]
https://protospace-32852.herokuapp.com/

**Comment by naokihayasan127** [comment]
提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎コメントを投稿すると、投稿したコメントとその投稿者名が表示されること
現在、コメントができない状態になっております。


◎ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること
ユーザーの詳細ページが閲覧できません。

◎現在、protospace自体がサーバーエラーで閲覧できなくなっております。
デプロイを見直しましょう。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by f-mio** [comment]
ご確認ありがとうございます。

確認したところ、コメント部分のrender処理でエラーが出ておりまして、該当部分を修正いたしました。その他にもrenderの使い方が間違っておりましたので修正いたしました。

ご確認よろしくお願いいたします。

**Comment by naokihayasan127** [comment]
再度、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by f-mio** [comment]
再度のご確認ありがとうございました！
